[rospy.client][INFO] 2017-05-22 12:25:41,597: init_node, name[/kuka_arm/spawner], pid[7168]
[xmlrpc][INFO] 2017-05-22 12:25:41,597: XML-RPC server binding to 0.0.0.0:0
[rospy.init][INFO] 2017-05-22 12:25:41,597: ROS Slave URI: [http://udacity:41601/]
[xmlrpc][INFO] 2017-05-22 12:25:41,597: Started XML-RPC server [http://udacity:41601/]
[rospy.impl.masterslave][INFO] 2017-05-22 12:25:41,597: _ready: http://udacity:41601/
[xmlrpc][INFO] 2017-05-22 12:25:41,598: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2017-05-22 12:25:41,598: Registering with master node http://localhost:11311
[rospy.init][INFO] 2017-05-22 12:25:41,697: registered with master
[rospy.rosout][INFO] 2017-05-22 12:25:41,698: initializing /rosout core topic
[rospy.rosout][INFO] 2017-05-22 12:25:41,699: connected to core topic /rosout
[rospy.simtime][INFO] 2017-05-22 12:25:41,700: initializing /clock core topic
[rospy.simtime][INFO] 2017-05-22 12:25:41,701: connected to core topic /clock
[rosout][INFO] 2017-05-22 12:25:41,704: Controller Spawner: Waiting for service controller_manager/load_controller
[rospy.internal][INFO] 2017-05-22 12:25:41,924: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2017-05-22 12:25:41,945: topic[/clock] adding connection to [http://udacity:39761/], count 0
[rosout][INFO] 2017-05-22 12:25:42,611: Controller Spawner: Waiting for service controller_manager/switch_controller
[rosout][INFO] 2017-05-22 12:25:42,612: Controller Spawner: Waiting for service controller_manager/unload_controller
[rosout][INFO] 2017-05-22 12:25:42,614: Loading controller: joint_state_controller
[rosout][INFO] 2017-05-22 12:25:42,718: Loading controller: arm_controller
[rosout][INFO] 2017-05-22 12:25:42,882: Loading controller: gripper_controller
[rosout][INFO] 2017-05-22 12:25:43,101: Controller Spawner: Loaded controllers: joint_state_controller, arm_controller, gripper_controller
[rosout][INFO] 2017-05-22 12:25:43,106: Started controllers: joint_state_controller, arm_controller, gripper_controller
[rospy.internal][INFO] 2017-05-22 12:27:55,000: topic[/rosout] removing connection to /rosout
[rospy.core][INFO] 2017-05-22 12:27:55,089: signal_shutdown [signal-2]
[rosout][INFO] 2017-05-22 12:27:55,089: Shutting down spawner. Stopping and unloading controllers...
[rospy.internal][ERROR] 2017-05-22 12:27:55,281: Unable to initiate TCP/IP socket to udacity:57343 (http://udacity:39761/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 57343 to [127.0.0.1:54512 on socket 9]] [/kuka_arm/spawner].

[rospy.internal][ERROR] 2017-05-22 12:27:56,282: Unable to initiate TCP/IP socket to udacity:57343 (http://udacity:39761/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 57343 to [127.0.0.1:58468 on socket 15]] [/kuka_arm/spawner].

[rospy.internal][ERROR] 2017-05-22 12:27:58,285: Unable to initiate TCP/IP socket to udacity:57343 (http://udacity:39761/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 57343 to [127.0.0.1:52634 on socket 15]] [/kuka_arm/spawner].

[rospy.internal][ERROR] 2017-05-22 12:28:02,287: Unable to initiate TCP/IP socket to udacity:57343 (http://udacity:39761/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 57343 to [127.0.0.1:52656 on socket 15]] [/kuka_arm/spawner].

[rospy.core][INFO] 2017-05-22 12:28:10,129: signal_shutdown [signal-15]
[rospy.internal][WARNING] 2017-05-22 12:28:10,289: Unknown error initiating TCP/IP socket to udacity:57343 (http://udacity:39761/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2017-05-22 12:28:10,290: topic[/clock] removing connection to http://udacity:39761/
