[rospy.client][INFO] 2017-05-22 12:25:41,415: init_node, name[/urdf_spawner], pid[7211]
[xmlrpc][INFO] 2017-05-22 12:25:41,416: XML-RPC server binding to 0.0.0.0:0
[rospy.init][INFO] 2017-05-22 12:25:41,416: ROS Slave URI: [http://udacity:38865/]
[xmlrpc][INFO] 2017-05-22 12:25:41,416: Started XML-RPC server [http://udacity:38865/]
[rospy.impl.masterslave][INFO] 2017-05-22 12:25:41,416: _ready: http://udacity:38865/
[xmlrpc][INFO] 2017-05-22 12:25:41,416: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2017-05-22 12:25:41,417: Registering with master node http://localhost:11311
[rospy.init][INFO] 2017-05-22 12:25:41,516: registered with master
[rospy.rosout][INFO] 2017-05-22 12:25:41,516: initializing /rosout core topic
[rospy.rosout][INFO] 2017-05-22 12:25:41,518: connected to core topic /rosout
[rospy.simtime][INFO] 2017-05-22 12:25:41,519: initializing /clock core topic
[rospy.simtime][INFO] 2017-05-22 12:25:41,521: connected to core topic /clock
[rosout][INFO] 2017-05-22 12:25:41,523: Loading model XML from ros parameter
[rosout][INFO] 2017-05-22 12:25:41,525: Waiting for service /gazebo/spawn_urdf_model
[rospy.internal][INFO] 2017-05-22 12:25:41,820: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2017-05-22 12:25:41,949: topic[/clock] adding connection to [http://udacity:39761/], count 0
[rosout][INFO] 2017-05-22 12:25:42,131: Calling service /gazebo/spawn_urdf_model
[rosout][INFO] 2017-05-22 12:25:42,312: Spawn status: SpawnModel: Successfully spawned entity
[rospy.core][INFO] 2017-05-22 12:25:42,312: signal_shutdown [atexit]
[rospy.internal][INFO] 2017-05-22 12:25:42,314: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2017-05-22 12:25:42,314: topic[/clock] removing connection to http://udacity:39761/
[rospy.topics][ERROR] 2017-05-22 12:25:42,315: Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 326, in close
    c.close()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 838, in close
    self.socket.close()
AttributeError: 'NoneType' object has no attribute 'close'

[rospy.impl.masterslave][INFO] 2017-05-22 12:25:42,315: atexit
[rospy.internal][WARNING] 2017-05-22 12:25:42,316: Unknown error initiating TCP/IP socket to udacity:57343 (http://udacity:39761/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

