[rospy.client][INFO] 2017-05-22 12:19:48,156: init_node, name[/target_spawner], pid[2298]
[xmlrpc][INFO] 2017-05-22 12:19:48,156: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2017-05-22 12:19:48,157: Started XML-RPC server [http://udacity:34857/]
[rospy.init][INFO] 2017-05-22 12:19:48,157: ROS Slave URI: [http://udacity:34857/]
[rospy.impl.masterslave][INFO] 2017-05-22 12:19:48,157: _ready: http://udacity:34857/
[xmlrpc][INFO] 2017-05-22 12:19:48,157: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2017-05-22 12:19:48,158: Registering with master node http://localhost:11311
[rospy.init][INFO] 2017-05-22 12:19:48,257: registered with master
[rospy.rosout][INFO] 2017-05-22 12:19:48,257: initializing /rosout core topic
[rospy.rosout][INFO] 2017-05-22 12:19:48,259: connected to core topic /rosout
[rospy.simtime][INFO] 2017-05-22 12:19:48,260: initializing /clock core topic
[rospy.simtime][INFO] 2017-05-22 12:19:48,269: connected to core topic /clock
[rosout][INFO] 2017-05-22 12:19:48,273: Loading model XML from ros parameter
[rosout][INFO] 2017-05-22 12:19:48,280: Waiting for service /gazebo/spawn_urdf_model
[rospy.internal][INFO] 2017-05-22 12:19:48,408: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2017-05-22 12:19:50,341: topic[/clock] adding connection to [http://udacity:45133/], count 0
[rosout][INFO] 2017-05-22 12:19:50,397: Calling service /gazebo/spawn_urdf_model
[rospy.core][INFO] 2017-05-22 12:20:34,575: signal_shutdown [atexit]
[rospy.internal][WARNING] 2017-05-22 12:20:34,578: Unknown error initiating TCP/IP socket to udacity:37877 (http://udacity:45133/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 362, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2017-05-22 12:20:34,578: topic[/clock] removing connection to http://udacity:45133/
[rospy.internal][INFO] 2017-05-22 12:20:34,579: topic[/rosout] removing connection to /rosout
[rospy.impl.masterslave][INFO] 2017-05-22 12:20:34,579: atexit
