[rospy.client][INFO] 2017-05-22 12:19:49,436: init_node, name[/urdf_spawner], pid[2387]
[xmlrpc][INFO] 2017-05-22 12:19:49,437: XML-RPC server binding to 0.0.0.0:0
[rospy.init][INFO] 2017-05-22 12:19:49,437: ROS Slave URI: [http://udacity:36175/]
[xmlrpc][INFO] 2017-05-22 12:19:49,437: Started XML-RPC server [http://udacity:36175/]
[rospy.impl.masterslave][INFO] 2017-05-22 12:19:49,440: _ready: http://udacity:36175/
[xmlrpc][INFO] 2017-05-22 12:19:49,440: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2017-05-22 12:19:49,441: Registering with master node http://localhost:11311
[rospy.init][INFO] 2017-05-22 12:19:49,539: registered with master
[rospy.rosout][INFO] 2017-05-22 12:19:49,539: initializing /rosout core topic
[rospy.rosout][INFO] 2017-05-22 12:19:49,542: connected to core topic /rosout
[rospy.simtime][INFO] 2017-05-22 12:19:49,545: initializing /clock core topic
[rospy.simtime][INFO] 2017-05-22 12:19:49,552: connected to core topic /clock
[rosout][INFO] 2017-05-22 12:19:49,583: Loading model XML from ros parameter
[rosout][INFO] 2017-05-22 12:19:49,603: Waiting for service /gazebo/spawn_urdf_model
[rospy.internal][INFO] 2017-05-22 12:19:49,812: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2017-05-22 12:19:50,338: topic[/clock] adding connection to [http://udacity:45133/], count 0
[rosout][INFO] 2017-05-22 12:19:50,522: Calling service /gazebo/spawn_urdf_model
[rospy.core][INFO] 2017-05-22 12:20:34,552: signal_shutdown [signal-2]
[rospy.internal][INFO] 2017-05-22 12:20:34,561: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2017-05-22 12:20:34,562: topic[/clock] removing connection to http://udacity:45133/
[rospy.impl.masterslave][INFO] 2017-05-22 12:20:34,562: signal-2
[rospy.internal][WARNING] 2017-05-22 12:20:34,578: Unknown error initiating TCP/IP socket to udacity:37877 (http://udacity:45133/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 362, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][ERROR] 2017-05-22 12:20:34,695: Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 729, in receive_once
    self.stat_bytes += recv_buff(sock, b, p.buff_size)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 103, in recv_buff
    d = sock.recv(buff_size)
error: [Errno 4] Interrupted system call

[rospy.core][INFO] 2017-05-22 12:20:34,696: signal_shutdown [atexit]
