[rospy.client][INFO] 2017-05-22 12:28:43,950: init_node, name[/kuka_arm/spawner], pid[9951]
[xmlrpc][INFO] 2017-05-22 12:28:43,950: XML-RPC server binding to 0.0.0.0:0
[rospy.init][INFO] 2017-05-22 12:28:43,952: ROS Slave URI: [http://udacity:37853/]
[xmlrpc][INFO] 2017-05-22 12:28:43,952: Started XML-RPC server [http://udacity:37853/]
[rospy.impl.masterslave][INFO] 2017-05-22 12:28:43,952: _ready: http://udacity:37853/
[xmlrpc][INFO] 2017-05-22 12:28:43,953: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2017-05-22 12:28:43,953: Registering with master node http://localhost:11311
[rospy.init][INFO] 2017-05-22 12:28:44,052: registered with master
[rospy.rosout][INFO] 2017-05-22 12:28:44,052: initializing /rosout core topic
[rospy.rosout][INFO] 2017-05-22 12:28:44,054: connected to core topic /rosout
[rospy.simtime][INFO] 2017-05-22 12:28:44,058: initializing /clock core topic
[rospy.simtime][INFO] 2017-05-22 12:28:44,061: connected to core topic /clock
[rosout][INFO] 2017-05-22 12:28:44,064: Controller Spawner: Waiting for service controller_manager/load_controller
[rospy.internal][INFO] 2017-05-22 12:28:44,069: topic[/clock] adding connection to [http://udacity:36725/], count 0
[rospy.internal][INFO] 2017-05-22 12:28:44,347: topic[/rosout] adding connection to [/rosout], count 0
[rosout][INFO] 2017-05-22 12:28:44,670: Controller Spawner: Waiting for service controller_manager/switch_controller
[rosout][INFO] 2017-05-22 12:28:44,671: Controller Spawner: Waiting for service controller_manager/unload_controller
[rosout][INFO] 2017-05-22 12:28:44,673: Loading controller: joint_state_controller
[rosout][INFO] 2017-05-22 12:28:45,008: Loading controller: arm_controller
[rosout][INFO] 2017-05-22 12:28:45,216: Loading controller: gripper_controller
[rosout][INFO] 2017-05-22 12:28:45,361: Controller Spawner: Loaded controllers: joint_state_controller, arm_controller, gripper_controller
[rosout][INFO] 2017-05-22 12:28:45,364: Started controllers: joint_state_controller, arm_controller, gripper_controller
[rospy.core][INFO] 2017-05-22 12:29:35,450: signal_shutdown [signal-2]
[rosout][INFO] 2017-05-22 12:29:35,451: Shutting down spawner. Stopping and unloading controllers...
[rospy.internal][ERROR] 2017-05-22 12:29:35,642: Unable to initiate TCP/IP socket to udacity:38445 (http://udacity:36725/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 38445 to [127.0.0.1:59134 on socket 17]] [/kuka_arm/spawner].

[rosout][INFO] 2017-05-22 12:29:36,455: Stopping all controllers...
[rospy.internal][ERROR] 2017-05-22 12:29:36,646: Unable to initiate TCP/IP socket to udacity:38445 (http://udacity:36725/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 38445 to [127.0.0.1:59488 on socket 17]] [/kuka_arm/spawner].

[rospy.internal][ERROR] 2017-05-22 12:29:38,647: Unable to initiate TCP/IP socket to udacity:38445 (http://udacity:36725/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 38445 to [127.0.0.1:59554 on socket 17]] [/kuka_arm/spawner].

[rospy.internal][INFO] 2017-05-22 12:29:39,089: topic[/rosout] removing connection to /rosout
[rospy.internal][ERROR] 2017-05-22 12:29:42,652: Unable to initiate TCP/IP socket to udacity:38445 (http://udacity:36725/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 38445 to [127.0.0.1:59564 on socket 17]] [/kuka_arm/spawner].

[rospy.core][INFO] 2017-05-22 12:29:50,489: signal_shutdown [signal-15]
[rospy.internal][ERROR] 2017-05-22 12:29:50,490: Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 729, in receive_once
    self.stat_bytes += recv_buff(sock, b, p.buff_size)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 103, in recv_buff
    d = sock.recv(buff_size)
error: [Errno 4] Interrupted system call

[rospy.core][INFO] 2017-05-22 12:29:50,491: signal_shutdown [atexit]
