[rospy.client][INFO] 2025-06-30 20:08:28,985: init_node, name[/turtlebot_teleop_keyboard], pid[23241]
[xmlrpc][INFO] 2025-06-30 20:08:28,985: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2025-06-30 20:08:28,985: Started XML-RPC server [http://192.168.1.124:41785/]
[rospy.impl.masterslave][INFO] 2025-06-30 20:08:28,986: _ready: http://192.168.1.124:41785/
[xmlrpc][INFO] 2025-06-30 20:08:28,986: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2025-06-30 20:08:28,986: Registering with master node http://localhost:11311
[rospy.init][INFO] 2025-06-30 20:08:28,991: ROS Slave URI: [http://192.168.1.124:41785/]
[rospy.init][INFO] 2025-06-30 20:08:28,991: registered with master
[rospy.rosout][INFO] 2025-06-30 20:08:28,991: initializing /rosout core topic
[rospy.rosout][INFO] 2025-06-30 20:08:28,993: connected to core topic /rosout
[rospy.simtime][INFO] 2025-06-30 20:08:28,995: initializing /clock core topic
[rospy.simtime][INFO] 2025-06-30 20:08:28,997: connected to core topic /clock
[rospy.internal][INFO] 2025-06-30 20:08:29,003: topic[/clock] adding connection to [http://192.168.1.124:45429/], count 0
[rospy.internal][INFO] 2025-06-30 20:08:29,213: topic[/cmd_vel_mux/input/teleop] adding connection to [/mobile_base_nodelet_manager], count 0
[rospy.internal][INFO] 2025-06-30 20:08:29,214: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2025-06-30 20:15:09,410: topic[/cmd_vel_mux/input/teleop] removing connection to /mobile_base_nodelet_manager
[rospy.internal][ERROR] 2025-06-30 20:15:09,515: Unable to initiate TCP/IP socket to 192.168.1.124:49991 (http://192.168.1.124:45429/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 558, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 651, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 594, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 49991 to [192.168.1.124:39384 on socket 15]] [/turtlebot_teleop_keyboard].

[rospy.internal][ERROR] 2025-06-30 20:15:10,517: Unable to initiate TCP/IP socket to 192.168.1.124:49991 (http://192.168.1.124:45429/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 558, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 651, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 594, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 49991 to [192.168.1.124:39490 on socket 15]] [/turtlebot_teleop_keyboard].

[rospy.internal][ERROR] 2025-06-30 20:15:12,518: Unable to initiate TCP/IP socket to 192.168.1.124:49991 (http://192.168.1.124:45429/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 558, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 651, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 594, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 49991 to [192.168.1.124:39492 on socket 15]] [/turtlebot_teleop_keyboard].

[rospy.internal][ERROR] 2025-06-30 20:15:16,522: Unable to initiate TCP/IP socket to 192.168.1.124:49991 (http://192.168.1.124:45429/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 558, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 651, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 594, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 49991 to [192.168.1.124:39494 on socket 15]] [/turtlebot_teleop_keyboard].

[rospy.internal][WARNING] 2025-06-30 20:15:24,528: Unknown error initiating TCP/IP socket to 192.168.1.124:49991 (http://192.168.1.124:45429/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 556, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2025-06-30 20:15:24,529: topic[/clock] removing connection to http://192.168.1.124:45429/
[rospy.internal][INFO] 2025-06-30 20:15:24,717: topic[/rosout] removing connection to /rosout
[rospy.core][INFO] 2025-06-30 20:17:11,728: signal_shutdown [atexit]
[rospy.impl.masterslave][INFO] 2025-06-30 20:17:11,731: atexit
