[rospy.client][INFO] 2025-06-06 13:13:24,602: init_node, name[/urdf_spawner], pid[29949]
[xmlrpc][INFO] 2025-06-06 13:13:24,602: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2025-06-06 13:13:24,602: Started XML-RPC server [http://192.168.1.124:45263/]
[rospy.init][INFO] 2025-06-06 13:13:24,602: ROS Slave URI: [http://192.168.1.124:45263/]
[rospy.impl.masterslave][INFO] 2025-06-06 13:13:24,603: _ready: http://192.168.1.124:45263/
[rospy.registration][INFO] 2025-06-06 13:13:24,603: Registering with master node http://localhost:11311
[xmlrpc][INFO] 2025-06-06 13:13:24,603: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2025-06-06 13:13:24,703: registered with master
[rospy.rosout][INFO] 2025-06-06 13:13:24,703: initializing /rosout core topic
[rospy.rosout][INFO] 2025-06-06 13:13:24,706: connected to core topic /rosout
[rospy.simtime][INFO] 2025-06-06 13:13:24,709: initializing /clock core topic
[rospy.simtime][INFO] 2025-06-06 13:13:24,711: connected to core topic /clock
[rosout][INFO] 2025-06-06 13:13:24,715: Loading model XML from ros parameter
[rosout][INFO] 2025-06-06 13:13:24,719: Waiting for service /gazebo/spawn_urdf_model
[rospy.internal][INFO] 2025-06-06 13:13:24,932: topic[/clock] adding connection to [http://192.168.1.124:44547/], count 0
[rospy.internal][INFO] 2025-06-06 13:13:24,997: topic[/rosout] adding connection to [/rosout], count 0
[rosout][INFO] 2025-06-06 13:13:25,022: Calling service /gazebo/spawn_urdf_model
[rosout][INFO] 2025-06-06 13:13:25,418: Spawn status: SpawnModel: Successfully spawned entity
[rospy.core][INFO] 2025-06-06 13:13:25,418: signal_shutdown [atexit]
[rospy.internal][INFO] 2025-06-06 13:13:25,420: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2025-06-06 13:13:25,421: topic[/clock] removing connection to http://192.168.1.124:44547/
[rospy.topics][ERROR] 2025-06-06 13:13:25,421: Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 326, in close
    c.close()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 838, in close
    self.socket.close()
AttributeError: 'NoneType' object has no attribute 'close'

[rospy.impl.masterslave][INFO] 2025-06-06 13:13:25,421: atexit
[rospy.internal][WARNING] 2025-06-06 13:13:25,421: Unknown error initiating TCP/IP socket to 192.168.1.124:54805 (http://192.168.1.124:44547/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

