[rospy.client][INFO] 2017-05-22 12:22:21,940: init_node, name[/target_spawner], pid[4935]
[xmlrpc][INFO] 2017-05-22 12:22:21,941: XML-RPC server binding to 0.0.0.0:0
[rospy.init][INFO] 2017-05-22 12:22:21,942: ROS Slave URI: [http://udacity:36371/]
[xmlrpc][INFO] 2017-05-22 12:22:21,942: Started XML-RPC server [http://udacity:36371/]
[rospy.impl.masterslave][INFO] 2017-05-22 12:22:21,942: _ready: http://udacity:36371/
[xmlrpc][INFO] 2017-05-22 12:22:21,943: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2017-05-22 12:22:21,945: Registering with master node http://localhost:11311
[rospy.init][INFO] 2017-05-22 12:22:22,042: registered with master
[rospy.rosout][INFO] 2017-05-22 12:22:22,042: initializing /rosout core topic
[rospy.rosout][INFO] 2017-05-22 12:22:22,044: connected to core topic /rosout
[rospy.simtime][INFO] 2017-05-22 12:22:22,046: initializing /clock core topic
[rospy.simtime][INFO] 2017-05-22 12:22:22,053: connected to core topic /clock
[rosout][INFO] 2017-05-22 12:22:22,064: Loading model XML from ros parameter
[rosout][INFO] 2017-05-22 12:22:22,066: Waiting for service /gazebo/spawn_urdf_model
[rospy.internal][INFO] 2017-05-22 12:22:22,232: topic[/rosout] adding connection to [/rosout], count 0
[rosout][INFO] 2017-05-22 12:22:23,276: Calling service /gazebo/spawn_urdf_model
[rospy.internal][INFO] 2017-05-22 12:22:23,376: topic[/clock] adding connection to [http://udacity:33881/], count 0
[rospy.core][INFO] 2017-05-22 12:22:55,689: signal_shutdown [atexit]
[rospy.internal][WARNING] 2017-05-22 12:22:55,691: Unknown error initiating TCP/IP socket to udacity:58415 (http://udacity:33881/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 362, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2017-05-22 12:22:55,691: topic[/clock] removing connection to http://udacity:33881/
[rospy.internal][INFO] 2017-05-22 12:22:55,701: topic[/rosout] removing connection to /rosout
[rospy.impl.masterslave][INFO] 2017-05-22 12:22:55,702: atexit
