[rospy.client][INFO] 2025-06-03 18:19:14,424: init_node, name[/urdf_spawner], pid[10191]
[xmlrpc][INFO] 2025-06-03 18:19:14,424: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2025-06-03 18:19:14,424: Started XML-RPC server [http://192.168.1.124:45913/]
[rospy.impl.masterslave][INFO] 2025-06-03 18:19:14,424: _ready: http://192.168.1.124:45913/
[xmlrpc][INFO] 2025-06-03 18:19:14,425: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2025-06-03 18:19:14,425: Registering with master node http://localhost:11311
[rospy.init][INFO] 2025-06-03 18:19:14,425: ROS Slave URI: [http://192.168.1.124:45913/]
[rospy.init][INFO] 2025-06-03 18:19:14,425: registered with master
[rospy.rosout][INFO] 2025-06-03 18:19:14,425: initializing /rosout core topic
[rospy.rosout][INFO] 2025-06-03 18:19:14,427: connected to core topic /rosout
[rospy.simtime][INFO] 2025-06-03 18:19:14,428: initializing /clock core topic
[rospy.simtime][INFO] 2025-06-03 18:19:14,431: connected to core topic /clock
[rosout][INFO] 2025-06-03 18:19:14,434: Loading model XML from ros parameter
[rosout][INFO] 2025-06-03 18:19:14,436: Waiting for service /gazebo/spawn_urdf_model
[rospy.internal][INFO] 2025-06-03 18:19:14,552: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2025-06-03 18:19:14,598: topic[/clock] adding connection to [http://192.168.1.124:34571/], count 0
[rosout][INFO] 2025-06-03 18:19:14,739: Calling service /gazebo/spawn_urdf_model
[rosout][INFO] 2025-06-03 18:19:15,347: Spawn status: SpawnModel: Successfully spawned entity
[rospy.core][INFO] 2025-06-03 18:19:15,347: signal_shutdown [atexit]
[rospy.internal][INFO] 2025-06-03 18:19:15,349: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2025-06-03 18:19:15,349: topic[/clock] removing connection to http://192.168.1.124:34571/
[rospy.topics][ERROR] 2025-06-03 18:19:15,351: Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 326, in close
    c.close()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 838, in close
    self.socket.close()
AttributeError: 'NoneType' object has no attribute 'close'

[rospy.internal][WARNING] 2025-06-03 18:19:15,351: Unknown error initiating TCP/IP socket to 192.168.1.124:32913 (http://192.168.1.124:34571/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.impl.masterslave][INFO] 2025-06-03 18:19:15,351: atexit
