[rospy.client][INFO] 2017-07-09 18:38:20,607: init_node, name[/kuka_arm/spawner], pid[11359]
[xmlrpc][INFO] 2017-07-09 18:38:20,607: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2017-07-09 18:38:20,608: Started XML-RPC server [http://udacity:46185/]
[rospy.init][INFO] 2017-07-09 18:38:20,608: ROS Slave URI: [http://udacity:46185/]
[rospy.impl.masterslave][INFO] 2017-07-09 18:38:20,608: _ready: http://udacity:46185/
[rospy.registration][INFO] 2017-07-09 18:38:20,609: Registering with master node http://localhost:11311
[xmlrpc][INFO] 2017-07-09 18:38:20,609: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2017-07-09 18:38:20,708: registered with master
[rospy.rosout][INFO] 2017-07-09 18:38:20,709: initializing /rosout core topic
[rospy.rosout][INFO] 2017-07-09 18:38:20,710: connected to core topic /rosout
[rospy.simtime][INFO] 2017-07-09 18:38:20,712: initializing /clock core topic
[rospy.simtime][INFO] 2017-07-09 18:38:20,715: connected to core topic /clock
[rosout][INFO] 2017-07-09 18:38:20,723: Controller Spawner: Waiting for service controller_manager/load_controller
[rospy.internal][INFO] 2017-07-09 18:38:20,886: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2017-07-09 18:38:21,138: topic[/clock] adding connection to [http://udacity:39353/], count 0
[rosout][INFO] 2017-07-09 18:38:21,931: Controller Spawner: Waiting for service controller_manager/switch_controller
[rosout][INFO] 2017-07-09 18:38:21,933: Controller Spawner: Waiting for service controller_manager/unload_controller
[rosout][INFO] 2017-07-09 18:38:21,938: Loading controller: joint_state_controller
[rosout][INFO] 2017-07-09 18:38:22,136: Loading controller: arm_controller
[rosout][INFO] 2017-07-09 18:38:22,309: Loading controller: gripper_controller
[rosout][INFO] 2017-07-09 18:38:22,642: Controller Spawner: Loaded controllers: joint_state_controller, arm_controller, gripper_controller
[rosout][INFO] 2017-07-09 18:38:22,647: Started controllers: joint_state_controller, arm_controller, gripper_controller
[rospy.core][INFO] 2017-07-09 19:11:15,301: signal_shutdown [signal-2]
[rosout][INFO] 2017-07-09 19:11:15,302: Shutting down spawner. Stopping and unloading controllers...
[rospy.internal][ERROR] 2017-07-09 19:11:15,511: Unable to initiate TCP/IP socket to udacity:51451 (http://udacity:39353/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 51451 to [127.0.0.1:48510 on socket 16]] [/kuka_arm/spawner].

[rosout][INFO] 2017-07-09 19:11:16,310: Stopping all controllers...
[rospy.internal][ERROR] 2017-07-09 19:11:16,513: Unable to initiate TCP/IP socket to udacity:51451 (http://udacity:39353/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 51451 to [127.0.0.1:48802 on socket 16]] [/kuka_arm/spawner].

[rospy.internal][ERROR] 2017-07-09 19:11:18,516: Unable to initiate TCP/IP socket to udacity:51451 (http://udacity:39353/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 51451 to [127.0.0.1:48884 on socket 16]] [/kuka_arm/spawner].

[rospy.internal][INFO] 2017-07-09 19:11:18,525: topic[/rosout] removing connection to /rosout
[rospy.internal][ERROR] 2017-07-09 19:11:22,517: Unable to initiate TCP/IP socket to udacity:51451 (http://udacity:39353/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 51451 to [127.0.0.1:48886 on socket 16]] [/kuka_arm/spawner].

[rospy.core][INFO] 2017-07-09 19:11:30,350: signal_shutdown [signal-15]
[rospy.internal][ERROR] 2017-07-09 19:11:30,350: Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 729, in receive_once
    self.stat_bytes += recv_buff(sock, b, p.buff_size)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 103, in recv_buff
    d = sock.recv(buff_size)
error: [Errno 4] Interrupted system call

[rospy.core][INFO] 2017-07-09 19:11:30,351: signal_shutdown [atexit]
